<a href="https://colab.research.google.com/github/savadarakeshreddy/aquaponics/blob/main/pond1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**importing the libraries**

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

**importing the dataset**

In [ ]:
data=pd.read_csv('IoTpond1.csv',parse_dates=['created_at'])
data.head()

,created_at,entry_id,Temperature (C),Turbidity(NTU),Dissolved Oxygen(g/ml),PH,Ammonia(g/ml),Nitrate(g/ml),Population,Fish_Length(cm),Fish_Weight(g)
0,2021-06-19 00:00:05,1889,24.8750,100,4.505,8.43365,0.45842,193,50,7.11,2.91
1,2021-06-19 00:01:02,1890,24.9375,100,6.601,8.43818,0.45842,194,50,7.11,2.91
2,2021-06-19 00:01:22,1891,24.8750,100,15.797,8.42457,0.45842,192,50,7.11,2.91
3,2021-06-19 00:01:44,1892,24.9375,100,5.046,8.43365,0.45842,193,50,7.11,2.91
4,2021-06-19 00:02:07,1893,24.9375,100,38.407,8.40641,0.45842,192,50,7.11,2.91

In [ ]:
columns_to_drop=['entry_id','Population']
data.drop(columns=columns_to_drop,axis=1,inplace=True)

In [ ]:
data['date']=data['created_at'].dt.date
data['time']=data['created_at'].dt.time
data.head()

,created_at,Temperature (C),Turbidity(NTU),Dissolved Oxygen(g/ml),PH,Ammonia(g/ml),Nitrate(g/ml),Fish_Length(cm),Fish_Weight(g),date,time
0,2021-06-19 00:00:05,24.8750,100,4.505,8.43365,0.45842,193,7.11,2.91,2021-06-19,00:00:05
1,2021-06-19 00:01:02,24.9375,100,6.601,8.43818,0.45842,194,7.11,2.91,2021-06-19,00:01:02
2,2021-06-19 00:01:22,24.8750,100,15.797,8.42457,0.45842,192,7.11,2.91,2021-06-19,00:01:22
3,2021-06-19 00:01:44,24.9375,100,5.046,8.43365,0.45842,193,7.11,2.91,2021-06-19,00:01:44
4,2021-06-19 00:02:07,24.9375,100,38.407,8.40641,0.45842,192,7.11,2.91,2021-06-19,00:02:07

In [ ]:
columns=data.columns.to_list()
columns=columns[-2:] + columns[:-2]
data=data[columns]
data.drop('created_at',axis=1,inplace=True)
data.head()

,date,time,Temperature (C),Turbidity(NTU),Dissolved Oxygen(g/ml),PH,Ammonia(g/ml),Nitrate(g/ml),Fish_Length(cm),Fish_Weight(g)
0,2021-06-19,00:00:05,24.8750,100,4.505,8.43365,0.45842,193,7.11,2.91
1,2021-06-19,00:01:02,24.9375,100,6.601,8.43818,0.45842,194,7.11,2.91
2,2021-06-19,00:01:22,24.8750,100,15.797,8.42457,0.45842,192,7.11,2.91
3,2021-06-19,00:01:44,24.9375,100,5.046,8.43365,0.45842,193,7.11,2.91
4,2021-06-19,00:02:07,24.9375,100,38.407,8.40641,0.45842,192,7.11,2.91

In [ ]:
data.shape

(83126, 10)

In [ ]:
data.isna().sum()

date                       0
time                       0
Temperature (C)            0
Turbidity(NTU)             0
Dissolved Oxygen(g/ml)     0
PH                         0
Ammonia(g/ml)             52
Nitrate(g/ml)              0
Fish_Length(cm)            2
Fish_Weight(g)             2
dtype: int64

In [ ]:
data['Ammonia(g/ml)'].mode()

0    0.45842
Name: Ammonia(g/ml), dtype: float64

In [ ]:
data['Ammonia(g/ml)'].replace([-np.inf,np.inf],np.nan,inplace=True)
from sklearn.impute import SimpleImputer
imputer=SimpleImputer(missing_values=np.nan,strategy='median')
data[['Ammonia(g/ml)']]=imputer.fit_transform(data[['Ammonia(g/ml)']])
data[['Fish_Length(cm)']]=imputer.fit_transform(data[['Fish_Length(cm)']])
data[['Fish_Weight(g)']]=imputer.fit_transform(data[['Fish_Weight(g)']])

In [ ]:
data["Ammonia(g/ml)"] = data["Ammonia(g/ml)"].replace(
    [x for x in data["Ammonia(g/ml)"] if x<0 or x > 0.21],0.2)

In [ ]:
data["Nitrate(g/ml)"] = data["Nitrate(g/ml)"].replace(
    [x for x in data["Nitrate(g/ml)"] if  x >400 or x<0], data['Nitrate(g/ml)'].median())

In [ ]:
data["Turbidity(NTU)"] = data["Turbidity(NTU)"].replace(
    [x for x in data["Turbidity(NTU)"] if x > 100 or x < 30], data['Turbidity(NTU)'].median())

In [ ]:
data["Temperature (C)"] = data["Temperature (C)"].replace(
    [x for x in data["Temperature (C)"] if x > 30 or x < 21], data['Temperature (C)'].median())

In [ ]:
data["PH"] = data["PH"].replace(
    [x for x in data["PH"] if x > 9 or x < 6.5], data['PH'].median())

In [ ]:
data["Dissolved Oxygen(g/ml)"] = data["Dissolved Oxygen(g/ml)"].replace(
    [x for x in data["Dissolved Oxygen(g/ml)"] if x>20 or x < 5], data['Dissolved Oxygen(g/ml)'].median())

In [ ]:
data['date']=data['date'].astype('category')
data['date']=data['date'].cat.codes
data.drop('time',axis=1,inplace=True)

In [ ]:
x=data.iloc[:,:-2].values
y=data.iloc[:,-1].values
y=y.reshape(len(y),1)

In [ ]:
print(x)

[[0.00000e+00 2.48750e+01 1.00000e+02 ... 8.43365e+00 2.00000e-01
  1.93000e+02]
 [0.00000e+00 2.49375e+01 1.00000e+02 ... 8.43818e+00 2.00000e-01
  1.94000e+02]
 [0.00000e+00 2.48750e+01 1.00000e+02 ... 8.42457e+00 2.00000e-01
  1.92000e+02]
 ...
 [8.00000e+01 2.65000e+01 1.00000e+02 ... 7.35779e+00 2.00000e-01
  3.47000e+02]
 [8.00000e+01 2.63750e+01 1.00000e+02 ... 7.35779e+00 2.00000e-01
  3.47000e+02]
 [8.00000e+01 2.63750e+01 1.00000e+02 ... 7.35779e+00 2.00000e-01
  3.47000e+02]]

In [ ]:
print(y)

[[  2.91]
 [  2.91]
 [  2.91]
 ...
 [318.64]
 [318.64]
 [318.64]]

In [ ]:
data.head()

,date,Temperature (C),Turbidity(NTU),Dissolved Oxygen(g/ml),PH,Ammonia(g/ml),Nitrate(g/ml),Fish_Length(cm),Fish_Weight(g)
0,0,24.8750,100,7.133,8.43365,0.2,193,7.11,2.91
1,0,24.9375,100,6.601,8.43818,0.2,194,7.11,2.91
2,0,24.8750,100,15.797,8.42457,0.2,192,7.11,2.91
3,0,24.9375,100,5.046,8.43365,0.2,193,7.11,2.91
4,0,24.9375,100,7.133,8.40641,0.2,192,7.11,2.91

splitting the dataset into training and testing

In [ ]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.25,random_state=0)

In [ ]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
x_train=sc.fit_transform(x_train)
x_test=sc.fit_transform(x_test)

In [ ]:
print(x_train)

[[ 0.61456768  0.07153487  0.51309259 ... -0.55041747  0.12553844
   1.14099572]
 [ 0.37877859 -0.56971052  0.51309259 ... -0.49857535  0.12553844
   1.1309565 ]
 [ 1.14509314 -2.03541428 -0.19641448 ... -0.93400349  0.12553844
   0.91009363]
 ...
 [ 0.26088404  2.27009051  0.51309259 ... -0.4778385   0.12553844
   0.56876011]
 [ 0.31983132  0.34635433  0.51309259 ... -0.59189117  0.12553844
   0.83981909]
 [ 1.0271986  -1.02774295 -0.31466565 ... -0.94437191  0.12553844
   0.91009363]]

training the model

In [ ]:
from sklearn.ensemble import RandomForestRegressor
regressor=RandomForestRegressor(n_estimators=100,random_state=0)
regressor.fit(x_train,y_train)

RandomForestRegressor(random_state=0)

predicting the model

In [ ]:
y_pred=regressor.predict(x_test)

In [ ]:
print(y_pred)

[64.88 24.82 47.71 ...  6.67  7.61 64.44]

In [ ]:
print(y_test)

[[64.88]
 [24.82]
 [47.71]
 ...
 [ 6.67]
 [ 7.61]
 [64.44]]

In [ ]:
from sklearn.metrics import r2_score,mean_squared_error
print(r2_score(y_test,y_pred))
mse=mean_squared_error(y_test,y_pred)
rmse=np.sqrt(mse)

0.9999979373738607

In [ ]:
print('MSE=',mse)
print('RMSE=',rmse)

MSE= 0.0022407913299971314
RMSE= 0.047336997475517305

In [ ]:
#decision tree

In [ ]:
from sklearn.tree import DecisionTreeRegressor
regressor=DecisionTreeRegressor(random_state=0)
regressor.fit(x_train,y_train)

DecisionTreeRegressor(random_state=0)

In [ ]:
y_pred=regressor.predict(x_test)

In [ ]:
from sklearn.metrics import r2_score
r2_score(y_test,y_pred)

0.9999957749763276

In [ ]:
mse=mean_squared_error(y_test,y_pred)
rmse=np.sqrt(mse)
print('MSE=',mse)
print('RMSE=',rmse)

MSE= 0.004589972091232515
RMSE= 0.06774933277333818

In [ ]:
#multiple linear regression

In [ ]:
from sklearn.linear_model import LinearRegression
regressor=LinearRegression()
regressor.fit(x_train,y_train)

LinearRegression()

In [ ]:
y_pred=regressor.predict(x_test)

In [ ]:
from sklearn.metrics import r2_score
r2_score(y_test,y_pred)

0.9113575870526468

In [ ]:
mse=mean_squared_error(y_test,y_pred)
rmse=np.sqrt(mse)
print('MSE=',mse)
print('RMSE=',rmse)

MSE= 96.29915311184878
RMSE= 9.813213189972425

In [ ]:
#polynomial regression

In [ ]:
from sklearn.preprocessing import PolynomialFeatures
from sklearn.linear_model import LinearRegression
poly=PolynomialFeatures(degree=3)
x_poly=poly.fit_transform(x_train)
regressor=LinearRegression()
regressor.fit(x_poly,y_train)

LinearRegression()

In [ ]:
y_pred=regressor.predict(poly.fit_transform(x_test))

In [ ]:
from sklearn.metrics import r2_score
r2_score(y_test,y_pred)

-544634590501.96954

In [ ]:
mse=mean_squared_error(y_test,y_pred)
rmse=np.sqrt(mse)
print('MSE=',mse)
print('RMSE=',rmse)

MSE= 591678950030439.1
RMSE= 24324451.69023218

In [ ]:
#ridge regression

In [ ]:
from sklearn.linear_model import Ridge
from sklearn.model_selection import GridSearchCV
ridge=Ridge()
parameters={'alpha':[1e-15,1e-10,1e-8,1e-3,1e-2,1,5,10,20,3035,40,45,50,55,100]}
ridge_regressor=GridSearchCV(ridge,parameters,cv=5)
ridge_regressor.fit(x_train,y_train)

GridSearchCV(cv=5, estimator=Ridge(),
             param_grid={'alpha': [1e-15, 1e-10, 1e-08, 0.001, 0.01, 1, 5, 10,
                                   20, 3035, 40, 45, 50, 55, 100]})

In [ ]:
y_pred=ridge_regressor.predict(x_test)
from sklearn.metrics import r2_score
r2_score(y_test,y_pred)

0.9113595839648496

In [ ]:
mse=mean_squared_error(y_test,y_pred)
rmse=np.sqrt(mse)
print('MSE=',mse)
print('RMSE=',rmse)

MSE= 96.29698371068326
RMSE= 9.813102654649205

In [ ]:
#lasso regression

In [ ]:
from sklearn.linear_model import Lasso
from sklearn.model_selection import GridSearchCV
lasso=Lasso()
parameters={'alpha':[1e-15,1e-10,1e-8,1e-3,1e-2,1,5,10,20,3035,40,45,50,55,100]}
lasso_regressor=GridSearchCV(lasso,parameters,cv=5)
lasso_regressor.fit(x_train,y_train)

GridSearchCV(cv=5, estimator=Lasso(),
             param_grid={'alpha': [1e-15, 1e-10, 1e-08, 0.001, 0.01, 1, 5, 10,
                                   20, 3035, 40, 45, 50, 55, 100]})

In [ ]:
y_pred=lasso_regressor.predict(x_test)
from sklearn.metrics import r2_score
r2_score(y_test,y_pred)

0.911361928781005

In [ ]:
mse=mean_squared_error(y_test,y_pred)
rmse=np.sqrt(mse)
print('MSE=',mse)
print('RMSE=',rmse)

MSE= 96.29443635437308
RMSE= 9.812972860166948

In [ ]:
#support vector regression

In [ ]:
from sklearn.svm import SVR
regressor = SVR(kernel = 'rbf')
regressor.fit(x_train, y_train)

SVR()

In [ ]:
y_pred=regressor.predict(x_test)
from sklearn.metrics import r2_score
r2_score(y_test,y_pred)

0.9721748824220734

In [ ]:
mse=mean_squared_error(y_test,y_pred)
rmse=np.sqrt(mse)
print('MSE=',mse)
print('RMSE=',rmse)

MSE= 30.22859113259236
RMSE= 5.49805339484734